version: '3.7'

services: 

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=genshin
    ports:
      - 3306:3306
    # utf8
    # command: mysql --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      # local path DB
      - ./mysqlDB:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 5555:80
    environment:
      - PMA_ARBITRARY=1

  # postgres:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=library
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=password
  #   ports: 
  #     - '5432:5432'
